// Auto-generated by EcoTrack development - 2025-09-27 14:16
// Add multi-tenant support

const update = {
  type: 'feat',
  scope: 'notifications',
  timestamp: '2025-09-27 14:16',
  description: 'Add multi-tenant support',
  author: 'Zakaria Talali',
  impact: 'medium'
};

module.exports = update;
